version: "2"

run:
  go: "1.25.6"

linters:
  enable:
    - boundarycontrol
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - dupl
    - readfriendlyorder
  settings:
    custom:
      boundarycontrol:
        type: "module"
        settings:
          architecture:
            plugin:
              imports: ["pkg/*"]
            pkg/*:
              imports: ["internal/*"]
      readfriendlyorder:
        type: "module"

linters-settings:
  dupl:
    threshold: 100

formatters:
  enable:
    - gofmt
    - goimports
