version: "2"

run:
  go: "1.25.6"

linters:
  enable:
    - gounslop
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - dupl
  settings:
    custom:
      gounslop:
        type: "module"
        settings:
          disable:
            - nospecialunicode
            - nounicodeescape
          architecture:
            plugin:
              imports: ["pkg/gounslop"]
            pkg/analyzer:
              shared: true
            pkg/gounslop:
              imports: ["pkg/*"]
            pkg/*:
              imports: ["pkg/analyzer"]
            tests:
              imports: ["pkg/gounslop"]

linters-settings:
  dupl:
    threshold: 100

formatters:
  enable:
    - gofmt
    - goimports
